# create a list of 50 random numbers

In [23]:
import random
arr = [random.randint(0,1000) for i in range(50)]
arr[:10]

[550, 46, 818, 15, 402, 804, 689, 753, 0, 848]

# Calculate square root


In [24]:
import math
%timeit [math.sqrt(a) for a in arr]

5.75 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# numpy 
1. Faster
1. Easy to use
2. Memory effecient
3. Rich in mathematical functions
4. Easy matrix operations

In [25]:

import numpy as np
numpy_arr = np.array(arr)
numpy_arr

array([550,  46, 818,  15, 402, 804, 689, 753,   0, 848, 266, 743, 257,
       712, 362, 260, 892, 535, 511,  15, 767, 137, 488, 204, 444, 893,
       528, 242, 903, 515, 411, 944,  54, 211, 417, 877,   7, 870, 390,
       923, 796, 591, 288, 794, 539, 141,  11, 843, 487, 344])

In [26]:
%timeit np.sqrt(numpy_arr)

813 ns ± 18.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Matrix operations

In [29]:
matrix_2d = np.random.randint(0,100,(2,3))
matrix_2d

array([[65, 14, 76],
       [89, 32,  5]])

In [32]:
matrix_2d.sum(axis = 0)

array([154,  46,  81])