@author : krishan subudhi

## create a list of 50 random numbers

In [5]:
import random
arr = [random.randint(0,1000) for i in range(50)]
arr[:10]

[342, 667, 185, 693, 147, 570, 770, 390, 331, 505]

## Calculate square root


In [6]:
import math
%timeit [math.sqrt(a) for a in arr]

20.9 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# numpy 
1. Faster
1. Easy to use
2. Memory effecient
3. Rich in mathematical functions
4. Easy matrix operations

In [8]:
import numpy as np
numpy_arr = np.array(arr)
numpy_arr[:10]

array([342, 667, 185, 693, 147, 570, 770, 390, 331, 505])

In [9]:
%timeit np.sqrt(numpy_arr)

2.82 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Matrix operations

In [10]:
matrix_2d = np.random.randint(0,100,(2,3))
matrix_2d

array([[ 6, 10, 26],
       [55, 91, 55]])

In [11]:
matrix_2d.sum(axis = 0)

array([ 61, 101,  81])